### ISSUE TITLE
Error de inicio

### ISSUE THREAD

**Issue by alvarmaciel** [makmm/manejador-de-tareas#4]
Hola.
Estoy probandolo, tengo este error, podrá ser la versión de node?

npm start

> manejador-de-tareas@1.0.0 start /home/alvar/git/manejador-de-tareas     
> node index.js   

sh: 1: node: not found               

npm ERR! manejador-de-tareas@1.0.0 start: `node index.js`                 
npm ERR! Exit status 127             
npm ERR!          
npm ERR! Failed at the manejador-de-tareas@1.0.0 start script.            
npm ERR! This is most likely a problem with the manejador-de-tareas package,
npm ERR! not with npm itself.        
npm ERR! Tell the author that this fails on your system:                  
npm ERR!     node index.js           
npm ERR! You can get their info via: 
npm ERR!     npm owner ls manejador-de-tareas                             
npm ERR! There is likely additional logging output above.                 
npm ERR! System Linux 4.9.0-3-amd64  
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"                 
npm ERR! cwd /home/alvar/git/manejador-de-tareas                          
npm ERR! node -v v4.8.3              
npm ERR! npm -v 1.4.21               
npm ERR! code ELIFECYCLE             
npm WARN This failure might be due to the use of legacy binary "node"     
npm WARN For further explanations, please read                            
/usr/share/doc/nodejs/README.Debian  
                  
npm ERR!          
npm ERR! Additional logging details can be found in:                      
npm ERR!     /home/alvar/git/manejador-de-tareas/npm-debug.log            
npm ERR! not ok code 0

**Comment by makmm** [comment]
Se ve que tenes node como nodejs,

```
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```
